# Generated by Django 4.1 on 2022-08-17 22:18

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuários',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='login_nick_name',
            field=models.CharField(default=' ', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='logradouro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='password',
            field=models.CharField(default='12345678', max_length=26, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AddField(
            model_name='usuários',
            name='primeiro_nome',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='usuários',
            name='sobrenome',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='usuários',
            name='tel_celular',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='usuários',
            name='tel_fixo',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='usuários',
            name='tipo',
            field=models.CharField(choices=[('C', 'Cliente'), ('A', 'Admin')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='usuários',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', ' Acre\t'), ('AL', 'Alagoas\t'), ('AP', 'Amapá\t'), ('AM', 'Amazonas\t'), ('BA', 'Bahia\t'), ('CE', 'Ceara\t'), ('DF', 'Distrito_Federal\t'), ('ES', 'Espírito_Santo\t'), ('GO', 'Goiás\t'), ('MA', 'Maranhão\t'), ('MT', 'Mato_Grosso'), ('MS', 'Mato_Grosso_do_Sul'), ('MG', 'Minas_Gerais'), ('PA', 'Pará\t'), ('PB', 'Paraíba\t '), ('PR', 'Paraná\t'), ('PE', 'Pernambuco\t'), ('PI', 'Piauí\t'), ('RJ', 'Rio_de_Janeiro\t  '), ('RN', 'Rio_Grande_do_Norte\t'), ('RS', 'Rio_Grande_do_Sul'), ('RO', 'Rondônia\t'), ('RR', 'Roraima'), ('SC', 'Santa_Catarina\t'), ('SP', 'São_Paulo\t'), ('SE', 'Sergipe\t'), ('TO', 'Tocantins')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuários',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
