# Generated by Django 4.1 on 2022-08-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuários_bairro_usuários_cidade_usuários_complemento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='s_categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Usuários',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
