# Generated by Django 4.1 on 2022-08-17 23:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_carrinho_delete_estoque_delete_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipos',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tipos'},
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('qtd_em_estoque', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cor', models.CharField(max_length=50)),
                ('tamanho', models.PositiveIntegerField()),
                ('imagem', models.ImageField(upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('s_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sub_categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
